use_frameworks!

platform :ios, '8.0'
    pod 'MJRefresh'
    pod 'MBProgressHUD'
    pod 'MJExtension'
    pod 'AFNetworking'
    pod 'SSKeychain'

target 'PLBase_Example' do
  pod 'PLBase', :path => '../'

  target 'PLBase_Tests' do
    inherit! :search_paths

    pod 'Specta'
    pod 'Expecta'
    pod 'FBSnapshotTestCase'
    pod 'Expecta+Snapshots'
  end
end
